CREATE TABLE IF NOT EXISTS searchIndex(id INTEGER PRIMARY KEY, name TEXT, type TEXT, path TEXT);
INSERT INTO searchIndex VALUES (NULL, 'Book', 'Guide', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, 'Download Ebook', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '1. Getting Started', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '2. Git Basics', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '3. Git Branching', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '4. Git on the Server', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '5. Distributed Git', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '6. GitHub', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '7. Git Tools', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '8. Customizing Git', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '9. Git and Other Systems', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '10. Git Internals', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, 'A1. Appendix A: Git in Other Environments', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, 'A2. Appendix B: Embedding Git in your Applications', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, 'A3. Appendix C: Git Commands', 'Section', 'git-scm.com/book/en/v2.html');
INSERT INTO searchIndex VALUES (NULL, '4.6 Git on the Server - Smart HTTP', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP.html');
INSERT INTO searchIndex VALUES (NULL, 'Smart HTTP', 'Section', 'git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Hooks', 'Section', 'git-scm.com/book/en/v2/ch00/_email_hooks.html');
INSERT INTO searchIndex VALUES (NULL, 'Recording Changes to the Repository', 'Section', 'git-scm.com/book/en/v2/ch00/_committing_changes.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Objects', 'Section', 'git-scm.com/book/en/v2/ch00/_git_commit_objects.html');
INSERT INTO searchIndex VALUES (NULL, 'Undoing Things', 'Section', 'git-scm.com/book/en/v2/ch00/_undoing.html');
INSERT INTO searchIndex VALUES (NULL, 'Working with Remotes', 'Section', 'git-scm.com/book/en/v2/ch00/_remote_repos.html');
INSERT INTO searchIndex VALUES (NULL, 'Contributing to a Project', 'Section', 'git-scm.com/book/en/v2/ch00/_task_list_progress.html');
INSERT INTO searchIndex VALUES (NULL, 'Revision Selection', 'Section', 'git-scm.com/book/en/v2/ch00/_branch_references.html');
INSERT INTO searchIndex VALUES (NULL, 'Rebasing', 'Section', 'git-scm.com/book/en/v2/ch00/rbdiag_e.html');
INSERT INTO searchIndex VALUES (NULL, 'Maintaining a Project', 'Section', 'git-scm.com/book/en/v2/ch00/_tagging_releases.html');
INSERT INTO searchIndex VALUES (NULL, 'Advanced Merging', 'Section', 'git-scm.com/book/en/v2/ch00/_checking_out_conflicts.html');
INSERT INTO searchIndex VALUES (NULL, 'Getting Help', 'Section', 'git-scm.com/book/en/v2/ch00/_git_help.html');
INSERT INTO searchIndex VALUES (NULL, 'Getting Git on a Server', 'Section', 'git-scm.com/book/en/v2/ch00/_bare_repo.html');
INSERT INTO searchIndex VALUES (NULL, 'Migrating to Git', 'Section', 'git-scm.com/book/en/v2/ch00/_custom_importer.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Configuration', 'Section', 'git-scm.com/book/en/v2/ch00/_external_merge_tools.html');
INSERT INTO searchIndex VALUES (NULL, 'Maintaining a Project', 'Section', 'git-scm.com/book/en/v2/ch00/_not_center.html');
INSERT INTO searchIndex VALUES (NULL, 'Reset Demystified', 'Section', 'git-scm.com/book/en/v2/ch00/_the_index.html');
INSERT INTO searchIndex VALUES (NULL, 'Rewriting History', 'Section', 'git-scm.com/book/en/v2/ch00/_changing_multiple.html');
INSERT INTO searchIndex VALUES (NULL, 'Contributing to a Project', 'Section', 'git-scm.com/book/en/v2/ch00/_contributing_project.html');
INSERT INTO searchIndex VALUES (NULL, 'Setting Up the Server', 'Section', 'git-scm.com/book/en/v2/ch00/_setting_up_server.html');
INSERT INTO searchIndex VALUES (NULL, 'Basic Branching and Merging', 'Section', 'git-scm.com/book/en/v2/ch00/_basic_branching.html');
INSERT INTO searchIndex VALUES (NULL, '1.1 Getting Started - About Version Control', 'Guide', 'git-scm.com/book/en/v2/ch00/ch01-getting-started.html');
INSERT INTO searchIndex VALUES (NULL, 'About Version Control', 'Section', 'git-scm.com/book/en/v2/ch00/ch01-getting-started.html');
INSERT INTO searchIndex VALUES (NULL, 'Debugging with Git', 'Section', 'git-scm.com/book/en/v2/ch00/_file_annotation.html');
INSERT INTO searchIndex VALUES (NULL, 'Libgit2', 'Section', 'git-scm.com/book/en/v2/ch00/_libgit2_bindings.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Attributes', 'Section', 'git-scm.com/book/en/v2/ch00/filters_a.html');
INSERT INTO searchIndex VALUES (NULL, 'Signing Your Work', 'Section', 'git-scm.com/book/en/v2/ch00/_signing.html');
INSERT INTO searchIndex VALUES (NULL, 'An Example Git-Enforced Policy', 'Section', 'git-scm.com/book/en/v2/ch00/_enforcing_commit_message_format.html');
INSERT INTO searchIndex VALUES (NULL, 'Replace', 'Section', 'git-scm.com/book/en/v2/ch00/_replace.html');
INSERT INTO searchIndex VALUES (NULL, 'Git as a Client', 'Section', 'git-scm.com/book/en/v2/ch00/_p4_git_fusion.html');
INSERT INTO searchIndex VALUES (NULL, 'Searching', 'Section', 'git-scm.com/book/en/v2/ch00/_searching.html');
INSERT INTO searchIndex VALUES (NULL, '10.1 Git Internals - Plumbing and Porcelain', 'Guide', 'git-scm.com/book/en/v2/ch00/ch10-git-internals.html');
INSERT INTO searchIndex VALUES (NULL, 'Plumbing and Porcelain', 'Section', 'git-scm.com/book/en/v2/ch00/ch10-git-internals.html');
INSERT INTO searchIndex VALUES (NULL, '2.1 Git Basics - Getting a Git Repository', 'Guide', 'git-scm.com/book/en/v2/ch00/ch02-git-basics-chapter.html');
INSERT INTO searchIndex VALUES (NULL, 'Getting a Git Repository', 'Section', 'git-scm.com/book/en/v2/ch00/ch02-git-basics-chapter.html');
INSERT INTO searchIndex VALUES (NULL, 'Branching Workflows', 'Section', 'git-scm.com/book/en/v2/ch00/_topic_branch.html');
INSERT INTO searchIndex VALUES (NULL, 'Remote Branches', 'Section', 'git-scm.com/book/en/v2/ch00/_tracking_branches.html');
INSERT INTO searchIndex VALUES (NULL, 'Scripting GitHub', 'Section', 'git-scm.com/book/en/v2/ch00/_api_comment.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Aliases', 'Section', 'git-scm.com/book/en/v2/ch00/_git_aliases.html');
INSERT INTO searchIndex VALUES (NULL, 'Credential Storage', 'Section', 'git-scm.com/book/en/v2/ch00/_credential_caching.html');
INSERT INTO searchIndex VALUES (NULL, 'First-Time Git Setup', 'Section', 'git-scm.com/book/en/v2/ch00/_first_time.html');
INSERT INTO searchIndex VALUES (NULL, 'Maintenance and Data Recovery', 'Section', 'git-scm.com/book/en/v2/ch00/_data_recovery.html');
INSERT INTO searchIndex VALUES (NULL, 'Viewing the Commit History', 'Section', 'git-scm.com/book/en/v2/ch00/log_options.html');
INSERT INTO searchIndex VALUES (NULL, 'Bundling', 'Section', 'git-scm.com/book/en/v2/ch00/_bundling.html');
INSERT INTO searchIndex VALUES (NULL, 'Tagging', 'Section', 'git-scm.com/book/en/v2/ch00/_sharing_tags.html');
INSERT INTO searchIndex VALUES (NULL, '5.1 Distributed Git - Distributed Workflows', 'Guide', 'git-scm.com/book/en/v2/ch00/ch05-distributed-git.html');
INSERT INTO searchIndex VALUES (NULL, 'Distributed Workflows', 'Section', 'git-scm.com/book/en/v2/ch00/ch05-distributed-git.html');
INSERT INTO searchIndex VALUES (NULL, 'Managing an organization', 'Section', 'git-scm.com/book/en/v2/ch00/_team_page.html');
INSERT INTO searchIndex VALUES (NULL, 'The Refspec', 'Section', 'git-scm.com/book/en/v2/ch00/_refspec.html');
INSERT INTO searchIndex VALUES (NULL, 'Rerere', 'Section', 'git-scm.com/book/en/v2/ch00/ref_rerere.html');
INSERT INTO searchIndex VALUES (NULL, 'Account Setup and Configuration', 'Section', 'git-scm.com/book/en/v2/ch00/_personal_avatar.html');
INSERT INTO searchIndex VALUES (NULL, 'Branch Management', 'Section', 'git-scm.com/book/en/v2/ch00/_branch_management.html');
INSERT INTO searchIndex VALUES (NULL, '6.1 GitHub - Account Setup and Configuration', 'Guide', 'git-scm.com/book/en/v2/ch00/ch06-github.html');
INSERT INTO searchIndex VALUES (NULL, 'Branches in a Nutshell', 'Section', 'git-scm.com/book/en/v2/ch00/_git_branches_overview.html');
INSERT INTO searchIndex VALUES (NULL, 'Git References', 'Section', 'git-scm.com/book/en/v2/ch00/ref_the_ref.html');
INSERT INTO searchIndex VALUES (NULL, 'Submodules', 'Section', 'git-scm.com/book/en/v2/ch00/_cloning_submodules.html');
INSERT INTO searchIndex VALUES (NULL, 'Stashing and Cleaning', 'Section', 'git-scm.com/book/en/v2/ch00/_git_clean.html');
INSERT INTO searchIndex VALUES (NULL, 'Git in Visual Studio', 'Section', 'git-scm.com/book/en/v2/ch00/vs_home.html');
INSERT INTO searchIndex VALUES (NULL, 'Interactive Staging', 'Section', 'git-scm.com/book/en/v2/ch00/_interactive_staging.html');
INSERT INTO searchIndex VALUES (NULL, '3.1 Git Branching - Branches in a Nutshell', 'Guide', 'git-scm.com/book/en/v2/ch00/ch03-git-branching.html');
INSERT INTO searchIndex VALUES (NULL, 'Git in Zsh', 'Section', 'git-scm.com/book/en/v2/ch00/oh_my_zsh_git.html');
INSERT INTO searchIndex VALUES (NULL, 'GitLab', 'Section', 'git-scm.com/book/en/v2/ch00/_gitlab_groups_section.html');
INSERT INTO searchIndex VALUES (NULL, 'Generating Your SSH Public Key', 'Section', 'git-scm.com/book/en/v2/ch00/_generate_ssh_key.html');
INSERT INTO searchIndex VALUES (NULL, '1.2 Getting Started - A Short History of Git', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git.html');
INSERT INTO searchIndex VALUES (NULL, 'A Short History of Git', 'Section', 'git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git.html');
INSERT INTO searchIndex VALUES (NULL, '5.3 Distributed Git - Maintaining a Project', 'Guide', 'git-scm.com/book/en/v2/Distributed-Git-Maintaining-a-Project.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.12 Appendix C: Git Commands - Plumbing Commands', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Plumbing-Commands.html');
INSERT INTO searchIndex VALUES (NULL, 'Plumbing Commands', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Plumbing-Commands.html');
INSERT INTO searchIndex VALUES (NULL, '10.3 Git Internals - Git References', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Git-References.html');
INSERT INTO searchIndex VALUES (NULL, '4.2 Git on the Server - Getting Git on a Server', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.9 Appendix C: Git Commands - Email', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Email.html');
INSERT INTO searchIndex VALUES (NULL, 'Email', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Email.html');
INSERT INTO searchIndex VALUES (NULL, '7.13 Git Tools - Replace', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Replace.html');
INSERT INTO searchIndex VALUES (NULL, '4.10 Git on the Server - Summary', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Git-on-the-Server-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '4.9 Git on the Server - Third Party Hosted Options', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Third-Party-Hosted-Options.html');
INSERT INTO searchIndex VALUES (NULL, 'Third Party Hosted Options', 'Section', 'git-scm.com/book/en/v2/Git-on-the-Server-Third-Party-Hosted-Options.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.5 Appendix C: Git Commands - Sharing and Updating Projects', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Sharing-and-Updating-Projects.html');
INSERT INTO searchIndex VALUES (NULL, 'Sharing and Updating Projects', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Sharing-and-Updating-Projects.html');
INSERT INTO searchIndex VALUES (NULL, '7.11 Git Tools - Submodules', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Submodules.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.2 Appendix A: Git in Other Environments - Git in Visual Studio', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Visual-Studio.html');
INSERT INTO searchIndex VALUES (NULL, '10.9 Git Internals - Summary', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Git-Internals-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '10.5 Git Internals - The Refspec', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-The-Refspec.html');
INSERT INTO searchIndex VALUES (NULL, '1.3 Getting Started - Git Basics', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-Git-Basics.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Basics', 'Section', 'git-scm.com/book/en/v2/Getting-Started-Git-Basics.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.4 Appendix A: Git in Other Environments - Git in Bash', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Bash.html');
INSERT INTO searchIndex VALUES (NULL, 'Git in Bash', 'Section', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Bash.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.4 Appendix C: Git Commands - Branching and Merging', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Branching-and-Merging.html');
INSERT INTO searchIndex VALUES (NULL, 'Branching and Merging', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Branching-and-Merging.html');
INSERT INTO searchIndex VALUES (NULL, '8.1 Customizing Git - Git Configuration', 'Guide', 'git-scm.com/book/en/v2/Customizing-Git-Git-Configuration.html');
INSERT INTO searchIndex VALUES (NULL, 'A2.1 Appendix B: Embedding Git in your Applications - Command-line Git', 'Guide', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-Command-line-Git.html');
INSERT INTO searchIndex VALUES (NULL, 'Command-line Git', 'Section', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-Command-line-Git.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.10 Appendix C: Git Commands - External Systems', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-External-Systems.html');
INSERT INTO searchIndex VALUES (NULL, 'External Systems', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-External-Systems.html');
INSERT INTO searchIndex VALUES (NULL, '2.6 Git Basics - Tagging', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Tagging.html');
INSERT INTO searchIndex VALUES (NULL, '4.8 Git on the Server - GitLab', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-GitLab.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.1 Appendix C: Git Commands - Setup and Config', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Setup-and-Config.html');
INSERT INTO searchIndex VALUES (NULL, 'Setup and Config', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Setup-and-Config.html');
INSERT INTO searchIndex VALUES (NULL, '6.5 GitHub - Scripting GitHub', 'Guide', 'git-scm.com/book/en/v2/GitHub-Scripting-GitHub.html');
INSERT INTO searchIndex VALUES (NULL, '2.8 Git Basics - Summary', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Git-Basics-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.6 Appendix A: Git in Other Environments - Git in Powershell', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Powershell.html');
INSERT INTO searchIndex VALUES (NULL, 'Git in Powershell', 'Section', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Powershell.html');
INSERT INTO searchIndex VALUES (NULL, '6.6 GitHub - Summary', 'Guide', 'git-scm.com/book/en/v2/GitHub-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/GitHub-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'A2.3 Appendix B: Embedding Git in your Applications - JGit', 'Guide', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-JGit.html');
INSERT INTO searchIndex VALUES (NULL, 'JGit', 'Section', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-JGit.html');
INSERT INTO searchIndex VALUES (NULL, '2.5 Git Basics - Working with Remotes', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes.html');
INSERT INTO searchIndex VALUES (NULL, '6.2 GitHub - Contributing to a Project', 'Guide', 'git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project.html');
INSERT INTO searchIndex VALUES (NULL, '10.6 Git Internals - Transfer Protocols', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols.html');
INSERT INTO searchIndex VALUES (NULL, 'Transfer Protocols', 'Section', 'git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols.html');
INSERT INTO searchIndex VALUES (NULL, '7.4 Git Tools - Signing Your Work', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.1 Appendix A: Git in Other Environments - Graphical Interfaces', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Graphical-Interfaces.html');
INSERT INTO searchIndex VALUES (NULL, 'Graphical Interfaces', 'Section', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Graphical-Interfaces.html');
INSERT INTO searchIndex VALUES (NULL, '4.3 Git on the Server - Generating Your SSH Public Key', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.7 Appendix C: Git Commands - Debugging', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Debugging.html');
INSERT INTO searchIndex VALUES (NULL, 'Debugging', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Debugging.html');
INSERT INTO searchIndex VALUES (NULL, '1.6 Getting Started - First-Time Git Setup', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.3 Appendix A: Git in Other Environments - Git in Eclipse', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Eclipse.html');
INSERT INTO searchIndex VALUES (NULL, 'Git in Eclipse', 'Section', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Eclipse.html');
INSERT INTO searchIndex VALUES (NULL, '4.5 Git on the Server - Git Daemon', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Git-Daemon.html');
INSERT INTO searchIndex VALUES (NULL, 'Git Daemon', 'Section', 'git-scm.com/book/en/v2/Git-on-the-Server-Git-Daemon.html');
INSERT INTO searchIndex VALUES (NULL, '4.1 Git on the Server - The Protocols', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols.html');
INSERT INTO searchIndex VALUES (NULL, 'The Protocols', 'Section', 'git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols.html');
INSERT INTO searchIndex VALUES (NULL, 'A2.5 Appendix B: Embedding Git in your Applications - Dulwich', 'Guide', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-Dulwich.html');
INSERT INTO searchIndex VALUES (NULL, 'Dulwich', 'Section', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-Dulwich.html');
INSERT INTO searchIndex VALUES (NULL, '2.3 Git Basics - Viewing the Commit History', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History.html');
INSERT INTO searchIndex VALUES (NULL, '7.14 Git Tools - Credential Storage', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Credential-Storage.html');
INSERT INTO searchIndex VALUES (NULL, 'A2.4 Appendix B: Embedding Git in your Applications - go-git', 'Guide', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-go-git.html');
INSERT INTO searchIndex VALUES (NULL, 'go-git', 'Section', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-go-git.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.7 Appendix A: Git in Other Environments - Summary', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '3.2 Git Branching - Basic Branching and Merging', 'Guide', 'git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging.html');
INSERT INTO searchIndex VALUES (NULL, '2.7 Git Basics - Git Aliases', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Git-Aliases.html');
INSERT INTO searchIndex VALUES (NULL, '3.6 Git Branching - Rebasing', 'Guide', 'git-scm.com/book/en/v2/Git-Branching-Rebasing.html');
INSERT INTO searchIndex VALUES (NULL, '2.2 Git Basics - Recording Changes to the Repository', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository.html');
INSERT INTO searchIndex VALUES (NULL, '7.15 Git Tools - Summary', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Git-Tools-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '7.12 Git Tools - Bundling', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Bundling.html');
INSERT INTO searchIndex VALUES (NULL, '8.2 Customizing Git - Git Attributes', 'Guide', 'git-scm.com/book/en/v2/Customizing-Git-Git-Attributes.html');
INSERT INTO searchIndex VALUES (NULL, '7.10 Git Tools - Debugging with Git', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.2 Appendix C: Git Commands - Getting and Creating Projects', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Getting-and-Creating-Projects.html');
INSERT INTO searchIndex VALUES (NULL, 'Getting and Creating Projects', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Getting-and-Creating-Projects.html');
INSERT INTO searchIndex VALUES (NULL, '5.4 Distributed Git - Summary', 'Guide', 'git-scm.com/book/en/v2/Distributed-Git-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Distributed-Git-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '7.5 Git Tools - Searching', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Searching.html');
INSERT INTO searchIndex VALUES (NULL, '7.7 Git Tools - Reset Demystified', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Reset-Demystified.html');
INSERT INTO searchIndex VALUES (NULL, '8.5 Customizing Git - Summary', 'Guide', 'git-scm.com/book/en/v2/Customizing-Git-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Customizing-Git-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '6.4 GitHub - Managing an organization', 'Guide', 'git-scm.com/book/en/v2/GitHub-Managing-an-organization.html');
INSERT INTO searchIndex VALUES (NULL, '1.5 Getting Started - Installing Git', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-Installing-Git.html');
INSERT INTO searchIndex VALUES (NULL, 'Installing Git', 'Section', 'git-scm.com/book/en/v2/Getting-Started-Installing-Git.html');
INSERT INTO searchIndex VALUES (NULL, 'A1.5 Appendix A: Git in Other Environments - Git in Zsh', 'Guide', 'git-scm.com/book/en/v2/Appendix-A_-Git-in-Other-Environments-Git-in-Zsh.html');
INSERT INTO searchIndex VALUES (NULL, '7.1 Git Tools - Revision Selection', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Revision-Selection.html');
INSERT INTO searchIndex VALUES (NULL, '1.7 Getting Started - Getting Help', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-Getting-Help.html');
INSERT INTO searchIndex VALUES (NULL, '4.7 Git on the Server - GitWeb', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-GitWeb.html');
INSERT INTO searchIndex VALUES (NULL, 'GitWeb', 'Section', 'git-scm.com/book/en/v2/Git-on-the-Server-GitWeb.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.8 Appendix C: Git Commands - Patching', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Patching.html');
INSERT INTO searchIndex VALUES (NULL, 'Patching', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Patching.html');
INSERT INTO searchIndex VALUES (NULL, '3.4 Git Branching - Branching Workflows', 'Guide', 'git-scm.com/book/en/v2/Git-Branching-Branching-Workflows.html');
INSERT INTO searchIndex VALUES (NULL, '3.3 Git Branching - Branch Management', 'Guide', 'git-scm.com/book/en/v2/Git-Branching-Branch-Management.html');
INSERT INTO searchIndex VALUES (NULL, '1.8 Getting Started - Summary', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Getting-Started-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '7.8 Git Tools - Advanced Merging', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Advanced-Merging.html');
INSERT INTO searchIndex VALUES (NULL, '3.7 Git Branching - Summary', 'Guide', 'git-scm.com/book/en/v2/Git-Branching-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Git-Branching-Summary.html');
INSERT INTO searchIndex VALUES (NULL, '7.6 Git Tools - Rewriting History', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Rewriting-History.html');
INSERT INTO searchIndex VALUES (NULL, '10.4 Git Internals - Packfiles', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Packfiles.html');
INSERT INTO searchIndex VALUES (NULL, 'Packfiles', 'Section', 'git-scm.com/book/en/v2/Git-Internals-Packfiles.html');
INSERT INTO searchIndex VALUES (NULL, '8.3 Customizing Git - Git Hooks', 'Guide', 'git-scm.com/book/en/v2/Customizing-Git-Git-Hooks.html');
INSERT INTO searchIndex VALUES (NULL, '4.4 Git on the Server - Setting Up the Server', 'Guide', 'git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server.html');
INSERT INTO searchIndex VALUES (NULL, '7.9 Git Tools - Rerere', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Rerere.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.6 Appendix C: Git Commands - Inspection and Comparison', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Inspection-and-Comparison.html');
INSERT INTO searchIndex VALUES (NULL, 'Inspection and Comparison', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Inspection-and-Comparison.html');
INSERT INTO searchIndex VALUES (NULL, '9.3 Git and Other Systems - Summary', 'Guide', 'git-scm.com/book/en/v2/Git-and-Other-Systems-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'Summary', 'Section', 'git-scm.com/book/en/v2/Git-and-Other-Systems-Summary.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.3 Appendix C: Git Commands - Basic Snapshotting', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Basic-Snapshotting.html');
INSERT INTO searchIndex VALUES (NULL, 'Basic Snapshotting', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Basic-Snapshotting.html');
INSERT INTO searchIndex VALUES (NULL, 'A2.2 Appendix B: Embedding Git in your Applications - Libgit2', 'Guide', 'git-scm.com/book/en/v2/Appendix-B_-Embedding-Git-in-your-Applications-Libgit2.html');
INSERT INTO searchIndex VALUES (NULL, '7.2 Git Tools - Interactive Staging', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Interactive-Staging.html');
INSERT INTO searchIndex VALUES (NULL, '10.8 Git Internals - Environment Variables', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Environment-Variables.html');
INSERT INTO searchIndex VALUES (NULL, 'Environment Variables', 'Section', 'git-scm.com/book/en/v2/Git-Internals-Environment-Variables.html');
INSERT INTO searchIndex VALUES (NULL, '8.4 Customizing Git - An Example Git-Enforced Policy', 'Guide', 'git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy.html');
INSERT INTO searchIndex VALUES (NULL, '9.2 Git and Other Systems - Migrating to Git', 'Guide', 'git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git.html');
INSERT INTO searchIndex VALUES (NULL, '1.4 Getting Started - The Command Line', 'Guide', 'git-scm.com/book/en/v2/Getting-Started-The-Command-Line.html');
INSERT INTO searchIndex VALUES (NULL, 'The Command Line', 'Section', 'git-scm.com/book/en/v2/Getting-Started-The-Command-Line.html');
INSERT INTO searchIndex VALUES (NULL, '6.3 GitHub - Maintaining a Project', 'Guide', 'git-scm.com/book/en/v2/GitHub-Maintaining-a-Project.html');
INSERT INTO searchIndex VALUES (NULL, '10.7 Git Internals - Maintenance and Data Recovery', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery.html');
INSERT INTO searchIndex VALUES (NULL, '9.1 Git and Other Systems - Git as a Client', 'Guide', 'git-scm.com/book/en/v2/Git-and-Other-Systems-Git-as-a-Client.html');
INSERT INTO searchIndex VALUES (NULL, 'A3.11 Appendix C: Git Commands - Administration', 'Guide', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Administration.html');
INSERT INTO searchIndex VALUES (NULL, 'Administration', 'Section', 'git-scm.com/book/en/v2/Appendix-C_-Git-Commands-Administration.html');
INSERT INTO searchIndex VALUES (NULL, '3.5 Git Branching - Remote Branches', 'Guide', 'git-scm.com/book/en/v2/Git-Branching-Remote-Branches.html');
INSERT INTO searchIndex VALUES (NULL, '10.2 Git Internals - Git Objects', 'Guide', 'git-scm.com/book/en/v2/Git-Internals-Git-Objects.html');
INSERT INTO searchIndex VALUES (NULL, '2.4 Git Basics - Undoing Things', 'Guide', 'git-scm.com/book/en/v2/Git-Basics-Undoing-Things.html');
INSERT INTO searchIndex VALUES (NULL, '7.3 Git Tools - Stashing and Cleaning', 'Guide', 'git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning.html');
INSERT INTO searchIndex VALUES (NULL, '5.2 Distributed Git - Contributing to a Project', 'Guide', 'git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project.html');
